# Generated by Django 3.1.3 on 2021-06-02 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konsultasi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Custumer',
            new_name='Asatid',
        ),
    ]
