# Generated by Django 3.1.3 on 2021-08-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konsultasi', '0005_auto_20210803_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='petugas',
            name='nik',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
