# Generated by Django 3.1.3 on 2021-08-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konsultasi', '0006_petugas_nik'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pakar',
            old_name='phone',
            new_name='id_pengguna',
        ),
        migrations.AddField(
            model_name='pakar',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pakar',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pakar',
            name='Jenis_kelamin',
            field=models.CharField(blank=True, choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=100, null=True),
        ),
    ]
