# Generated by Django 3.1.3 on 2021-08-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konsultasi', '0007_auto_20210809_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masyarakat',
            old_name='phone',
            new_name='id_pengguna',
        ),
        migrations.AddField(
            model_name='masyarakat',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='masyarakat',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='masyarakat',
            name='Jenis_kelamin',
            field=models.CharField(blank=True, choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='masyarakat',
            name='nama_lengkap',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pakar',
            name='nama_lengkap',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
