# Generated by Django 3.1.3 on 2021-08-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konsultasi', '0009_konsultasi_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='konsultasi_chat',
        ),
    ]
