# Generated by Django 3.1.3 on 2021-08-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konsultasi', '0010_delete_konsultasi_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='konsultasi_chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pesan', models.CharField(blank=True, max_length=200, null=True)),
                ('id_konsultasi', models.CharField(blank=True, max_length=50, null=True)),
                ('id_pengguna', models.CharField(blank=True, max_length=200, null=True)),
                ('petugas', models.CharField(blank=True, max_length=200, null=True)),
                ('isi', models.CharField(blank=True, max_length=2200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
