# Generated by Django 3.1.3 on 2021-08-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konsultasi', '0013_religius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='religius',
            name='jam',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
