# Generated by Django 3.1.3 on 2021-08-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konsultasi', '0014_auto_20210819_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='religius',
            name='jam',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='religius',
            name='tanggal',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
